/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/ThreeD/AugmentedRealityControl.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AugmentedRealityControl(props) {
  const { nodes, materials } = useGLTF('../../../assets/ThreeD/AugmentedRealityControl.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.333}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Oculus_Headset_Headset_0.geometry} material={materials.Headset} />
            <mesh geometry={nodes.Oculus_Headset_Headset_0001.geometry} material={materials.Headset} />
            <mesh geometry={nodes.Oculus_Headset_Headset_0002.geometry} material={materials.Headset} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../assets/ThreeD/AugmentedRealityControl.glb')