/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/ThreeD/EclipseRobot.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EclipseRobot(props) {
  const { nodes, materials } = useGLTF('../../../assets/ThreeD/EclipseRobot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.canopy_top.geometry} material={materials.texture} position={[0.021, 0.823, -0.286]} scale={0.001} />
      <mesh geometry={nodes.canopy_right.geometry} material={materials.texture} position={[0.375, 0.603, -0.279]} scale={0.001} />
      <mesh geometry={nodes.canopy_left.geometry} material={materials.texture} position={[-0.375, 0.603, -0.279]} scale={0.001} />
      <mesh geometry={nodes.canopy_front_1.geometry} material={materials.texture} position={[0.002, 0.519, -0.108]} scale={0.001} />
      <mesh geometry={nodes.canopy_front_2.geometry} material={materials.texture} position={[0, 0.755, -0.108]} scale={0.001} />
      <mesh geometry={nodes.Body12.geometry} material={materials.texture} position={[-0.001, 0.745, -0.438]} scale={0.001} />
      <mesh geometry={nodes.Body13.geometry} material={materials.texture} position={[-0.007, 0.511, -0.438]} scale={0.001} />
      <mesh geometry={nodes.Body14.geometry} material={materials.black_metal_1} position={[0, 0.746, -0.373]} scale={0.001} />
      <mesh geometry={nodes.Body9.geometry} material={materials.texture_2} position={[0.088, 0.068, -0.344]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body10.geometry} material={materials.texture_2} position={[-0.086, 0.068, -0.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body11.geometry} material={materials.texture_2} position={[-0.086, 0.068, -0.344]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body12001.geometry} material={materials.texture_2} position={[0.088, 0.068, -0.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body25.geometry} material={materials.texture_2} position={[0.19, 0.262, 0.385]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body26.geometry} material={materials.texture_2} position={[0.19, 0.347, 0.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body27.geometry} material={materials.texture_2} position={[0.19, 0.342, 0.356]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body28.geometry} material={materials.texture_2} position={[0.19, 0.337, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body29.geometry} material={materials.texture_2} position={[0.19, 0.339, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body30.geometry} material={materials.texture_2} position={[0.188, 0.344, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body31.geometry} material={materials.texture_2} position={[0.183, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body32.geometry} material={materials.texture_2} position={[0.181, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body33.geometry} material={materials.texture_2} position={[0.171, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body34.geometry} material={materials.texture_2} position={[0.161, 0.346, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body35.geometry} material={materials.texture_2} position={[0.171, 0.346, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body36.geometry} material={materials.texture_2} position={[0.181, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body37.geometry} material={materials.texture_2} position={[0.183, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body38.geometry} material={materials.texture_2} position={[0.188, 0.344, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body39.geometry} material={materials.texture_2} position={[0.19, 0.339, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body40.geometry} material={materials.texture_2} position={[0.19, 0.337, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body41.geometry} material={materials.texture_2} position={[0.19, 0.342, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body42.geometry} material={materials.texture_2} position={[0.19, 0.347, -0.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body43.geometry} material={materials.texture_2} position={[0.19, 0.317, -0.325]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body44.geometry} material={materials.texture_2} position={[0.19, 0.18, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body45.geometry} material={materials.texture_2} position={[0.188, 0.07, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body46.geometry} material={materials.texture_2} position={[0.001, 0.068, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body47.geometry} material={materials.texture_2} position={[-0.186, 0.07, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body48.geometry} material={materials.texture_2} position={[-0.187, 0.18, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body49.geometry} material={materials.texture_2} position={[-0.187, 0.317, -0.325]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body50.geometry} material={materials.texture_2} position={[-0.187, 0.347, -0.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body51.geometry} material={materials.texture_2} position={[-0.187, 0.342, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body52.geometry} material={materials.texture_2} position={[-0.187, 0.337, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body53.geometry} material={materials.texture_2} position={[-0.187, 0.339, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body54.geometry} material={materials.texture_2} position={[-0.186, 0.344, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body55.geometry} material={materials.texture_2} position={[-0.181, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body56.geometry} material={materials.texture_2} position={[-0.178, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body57.geometry} material={materials.texture_2} position={[-0.169, 0.346, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body58.geometry} material={materials.texture_2} position={[-0.159, 0.346, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body59.geometry} material={materials.texture_2} position={[-0.169, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body60.geometry} material={materials.texture_2} position={[-0.178, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body61.geometry} material={materials.texture_2} position={[-0.181, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body62.geometry} material={materials.texture_2} position={[-0.186, 0.344, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body63.geometry} material={materials.texture_2} position={[-0.187, 0.339, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body64.geometry} material={materials.texture_2} position={[-0.187, 0.337, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body65.geometry} material={materials.texture_2} position={[-0.187, 0.342, 0.356]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body66.geometry} material={materials.texture_2} position={[-0.187, 0.347, 0.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body67.geometry} material={materials.texture_2} position={[-0.187, 0.262, 0.385]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body68.geometry} material={materials.texture_2} position={[-0.187, 0.123, 0.337]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body69.geometry} material={materials.texture_2} position={[-0.187, 0.068, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body70.geometry} material={materials.texture_2} position={[-0.187, 0.068, 0.286]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body71.geometry} material={materials.texture_2} position={[-0.187, 0.073, 0.286]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body72.geometry} material={materials.texture_2} position={[-0.187, 0.077, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body73.geometry} material={materials.texture_2} position={[-0.187, 0.075, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body74.geometry} material={materials.texture_2} position={[-0.186, 0.07, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body75.geometry} material={materials.texture_2} position={[-0.181, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body76.geometry} material={materials.texture_2} position={[-0.178, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body77.geometry} material={materials.texture_2} position={[0.001, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body78.geometry} material={materials.texture_2} position={[0.181, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body79.geometry} material={materials.texture_2} position={[0.183, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body80.geometry} material={materials.texture_2} position={[0.188, 0.07, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body81.geometry} material={materials.texture_2} position={[0.19, 0.075, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body82.geometry} material={materials.texture_2} position={[0.19, 0.077, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body83.geometry} material={materials.texture_2} position={[0.19, 0.073, 0.286]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body84.geometry} material={materials.texture_2} position={[0.19, 0.068, 0.286]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body85.geometry} material={materials.texture_2} position={[0.19, 0.068, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body98.geometry} material={materials.texture_2} position={[0.19, 0.123, 0.337]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body99.geometry} material={materials.texture_2} position={[0.188, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body100.geometry} material={materials.texture_2} position={[-0.186, 0.149, 0.019]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body101.geometry} material={materials.texture_2} position={[-0.175, 0.344, 0.034]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body102.geometry} material={materials.texture_2} position={[-0.186, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body103.geometry} material={materials.texture_2} position={[0.181, 0.344, 0.034]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body104.geometry} material={materials.texture_2} position={[0.188, 0.149, 0.019]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body105.geometry} material={materials.texture_2} position={[0.001, 0.07, -0.271]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body106.geometry} material={materials.texture_2} position={[-0.185, 0.343, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body107.geometry} material={materials.texture_2} position={[0.187, 0.343, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body108.geometry} material={materials.texture_2} position={[-0.185, 0.071, -0.04]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body109.geometry} material={materials.texture_2} position={[0.187, 0.071, -0.04]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body110.geometry} material={materials.texture_2} position={[0.191, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body111.geometry} material={materials.texture_2} position={[-0.189, 0.149, 0.019]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body112.geometry} material={materials.texture_2} position={[-0.175, 0.347, 0.034]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body113.geometry} material={materials.texture_2} position={[-0.189, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body114.geometry} material={materials.texture_2} position={[0.181, 0.347, 0.034]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body115.geometry} material={materials.texture_2} position={[0.191, 0.149, 0.019]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body116.geometry} material={materials['military green']} position={[0.001, 0.067, -0.271]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body117.geometry} material={materials.texture_2} position={[-0.187, 0.345, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body118.geometry} material={materials.texture_2} position={[0.189, 0.345, 0.05]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body119.geometry} material={materials.texture_2} position={[-0.187, 0.069, -0.04]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body120.geometry} material={materials.texture_2} position={[0.189, 0.069, -0.04]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body121.geometry} material={materials.texture_2} position={[0.088, 0.068, -0.259]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body122.geometry} material={materials.texture_2} position={[-0.086, 0.068, -0.339]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body123.geometry} material={materials.texture_2} position={[-0.086, 0.068, -0.259]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body124.geometry} material={materials.texture_2} position={[0.088, 0.068, -0.339]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body1001.geometry} material={materials.texture_2} position={[-0.043, 0.204, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body2001.geometry} material={materials.texture_2} position={[-0.013, 0.204, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body3001.geometry} material={materials.texture_2} position={[0.037, 0.204, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body4001.geometry} material={materials.texture_2} position={[-0.024, 0.204, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body5001.geometry} material={materials.texture_2} position={[-0.186, 0.316, -0.323]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body6001.geometry} material={materials.texture_2} position={[-0.186, 0.286, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body7001.geometry} material={materials.texture_2} position={[-0.186, 0.178, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body8001.geometry} material={materials.texture_2} position={[0.001, 0.07, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body9001.geometry} material={materials.texture_2} position={[0.188, 0.178, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body10001.geometry} material={materials.texture_2} position={[0.188, 0.286, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body11001.geometry} material={materials.texture_2} position={[0.188, 0.316, -0.323]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body12002.geometry} material={materials.texture_2} position={[0.188, 0.345, -0.284]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body13002.geometry} material={materials.texture_2} position={[0.188, 0.346, -0.269]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body14002.geometry} material={materials.texture_2} position={[0.001, 0.346, -0.255]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body15001.geometry} material={materials.texture_2} position={[-0.186, 0.346, -0.269]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body16001.geometry} material={materials.texture_2} position={[-0.186, 0.345, -0.284]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body17001.geometry} material={materials.texture_2} position={[0.001, 0.344, -0.269]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body18001.geometry} material={materials.texture_2} position={[-0.011, 0.19, -0.362]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body19001.geometry} material={materials.texture_2} position={[0.001, 0.315, -0.323]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body20001.geometry} material={materials.texture_2} position={[0.001, 0.285, -0.361]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body21001.geometry} material={materials.texture_2} position={[0.001, 0.344, -0.284]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body22001.geometry} material={materials.texture_2} position={[0.001, 0.347, -0.269]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body23001.geometry} material={materials['military green']} position={[-0.011, 0.19, -0.365]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body24001.geometry} material={materials.texture_2} position={[0.001, 0.317, -0.324]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body25001.geometry} material={materials.texture_2} position={[0.001, 0.286, -0.364]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body26001.geometry} material={materials.texture_2} position={[0.001, 0.347, -0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body27001.geometry} material={materials.texture_2} position={[0.187, 0.071, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body28001.geometry} material={materials.texture_2} position={[-0.185, 0.071, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body29001.geometry} material={materials.texture_2} position={[-0.034, 0.203, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body30001.geometry} material={materials.texture_2} position={[-0.022, 0.244, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body31001.geometry} material={materials.texture_2} position={[0.001, 0.23, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body32001.geometry} material={materials.texture_2} position={[0.024, 0.244, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body33001.geometry} material={materials.texture_2} position={[0.001, 0.257, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body34001.geometry} material={materials.texture_2} position={[0.025, 0.203, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body35001.geometry} material={materials.texture_2} position={[-0.015, 0.203, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body36001.geometry} material={materials.texture_2} position={[-0.045, 0.203, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body1002.geometry} material={materials.texture_2} position={[0.188, 0.26, 0.384]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body3002.geometry} material={materials.texture_2} position={[0.188, 0.122, 0.334]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body4002.geometry} material={materials.texture_2} position={[0.001, 0.069, 0.286]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body5002.geometry} material={materials.texture_2} position={[-0.186, 0.122, 0.334]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body7002.geometry} material={materials.texture_2} position={[-0.186, 0.26, 0.384]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body8002.geometry} material={materials.texture_2} position={[-0.186, 0.344, 0.382]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body9002.geometry} material={materials.texture_2} position={[-0.186, 0.346, 0.367]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body10002.geometry} material={materials.texture_2} position={[0.001, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body11002.geometry} material={materials.texture_2} position={[0.188, 0.346, 0.367]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body12003.geometry} material={materials.texture_2} position={[0.188, 0.344, 0.382]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body13003.geometry} material={materials.texture_2} position={[0.001, 0.344, 0.367]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body14003.geometry} material={materials.texture_2} position={[0.001, 0.26, 0.382]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body15002.geometry} material={materials.texture_2} position={[0.001, 0.123, 0.333]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body16002.geometry} material={materials.texture_2} position={[0.001, 0.343, 0.381]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body17002.geometry} material={materials.texture_2} position={[0.001, 0.178, 0.382]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body18002.geometry} material={materials.texture_2} position={[0.001, 0.347, 0.367]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body19002.geometry} material={materials.Material} position={[0.001, 0.26, 0.385]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body20002.geometry} material={materials.Material} position={[0.001, 0.121, 0.335]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body21002.geometry} material={materials.texture_2} position={[0.001, 0.345, 0.383]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body22002.geometry} material={materials.texture_2} position={[0.001, 0.177, 0.385]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body1008.geometry} material={materials['Opaque(255,255,255)']} position={[0.089, 0.127, -0.302]} rotation={[1.733, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body3008.geometry} material={materials.texture_2} position={[0.124, 0.135, -0.291]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body4008.geometry} material={materials.texture_2} position={[0.124, 0.122, -0.303]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body15006.geometry} material={materials.texture_2} position={[0.124, 0.138, -0.31]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body16006.geometry} material={materials.texture_2} position={[0.079, 0.129, -0.302]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body17006.geometry} material={materials.texture_2} position={[0.124, 0.14, -0.304]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body18006.geometry} material={materials.texture_2} position={[0.124, 0.139, -0.296]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body19006.geometry} material={materials.texture_2} position={[0.124, 0.138, -0.3]} rotation={[1.733, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body21006.geometry} material={materials['Opaque(255,255,255)']} position={[0.089, 0.132, -0.302]} rotation={[1.733, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body1009.geometry} material={materials['Material.006']} position={[-0.089, 0.089, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body2009.geometry} material={materials['Material.006']} position={[-0.159, 0.089, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body3009.geometry} material={materials['Material.006']} position={[-0.159, 0.193, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body4009.geometry} material={materials['Material.006']} position={[-0.089, 0.193, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body5009.geometry} material={materials['Material.006']} position={[-0.086, 0.142, -0.259]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body6009.geometry} material={materials['Material.006']} position={[-0.086, 0.142, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body7009.geometry} material={materials['Material.006']} position={[-0.156, 0.142, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body8009.geometry} material={materials['Material.006']} position={[-0.156, 0.142, -0.259]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body9009.geometry} material={materials['Material.006']} position={[-0.166, 0.151, -0.303]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body10009.geometry} material={materials['Material.006']} position={[-0.076, 0.151, -0.301]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body11009.geometry} material={materials['Material.006']} position={[-0.121, 0.122, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body12010.geometry} material={materials['Material.006']} position={[-0.121, 0.136, -0.292]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body13009.geometry} material={materials['Material.006']} position={[-0.121, 0.097, -0.242]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body14009.geometry} material={materials['Material.006']} position={[-0.164, 0.131, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body15007.geometry} material={materials['Material.006']} position={[-0.077, 0.131, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body16007.geometry} material={materials['Material.006']} position={[-0.121, 0.07, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body17007.geometry} material={materials['Material.006']} position={[-0.121, 0.141, -0.362]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body18007.geometry} material={materials['Material.006']} position={[-0.121, 0.214, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body19007.geometry} material={materials['Material.006']} position={[-0.121, 0.136, -0.311]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body20007.geometry} material={materials['Material.006']} position={[-0.121, 0.143, -0.306]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body21007.geometry} material={materials['Material.006']} position={[-0.121, 0.145, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body22006.geometry} material={materials['Material.006']} position={[-0.121, 0.143, -0.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body23005.geometry} material={materials['Material.006']} position={[-0.075, 0.129, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body24005.geometry} material={materials['Material.006']} position={[-0.076, 0.108, -0.303]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body25003.geometry} material={materials['Material.006']} position={[-0.167, 0.129, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body26003.geometry} material={materials['Material.006']} position={[-0.166, 0.108, -0.301]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body27003.geometry} material={materials['Material.006']} position={[-0.07, 0.231, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body28003.geometry} material={materials['Material.006']} position={[-0.121, 0.235, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body29003.geometry} material={materials['Material.006']} position={[-0.172, 0.231, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body30003.geometry} material={materials['Material.006']} position={[-0.176, 0.18, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body31003.geometry} material={materials['Material.006']} position={[-0.172, 0.128, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body32003.geometry} material={materials['Material.006']} position={[-0.121, 0.125, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body33003.geometry} material={materials['Material.006']} position={[-0.07, 0.128, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body34003.geometry} material={materials['Material.006']} position={[-0.066, 0.18, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body35003.geometry} material={materials['Material.006']} position={[-0.121, 0.178, -0.242]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body36003.geometry} material={materials['Material.006']} position={[-0.156, 0.142, -0.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body37002.geometry} material={materials['Material.006']} position={[-0.156, 0.142, -0.344]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body38002.geometry} material={materials['Material.006']} position={[-0.086, 0.142, -0.344]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body39002.geometry} material={materials['Material.006']} position={[-0.086, 0.142, -0.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body40002.geometry} material={materials['Material.006']} position={[-0.083, 0.194, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body41002.geometry} material={materials['Material.006']} position={[-0.086, 0.194, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body42002.geometry} material={materials['Material.006']} position={[-0.153, 0.194, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body43002.geometry} material={materials['Material.006']} position={[-0.156, 0.194, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body44002.geometry} material={materials['Material.006']} position={[-0.153, 0.09, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body45002.geometry} material={materials['Material.006']} position={[-0.156, 0.09, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body46002.geometry} material={materials['Material.006']} position={[-0.083, 0.09, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body47002.geometry} material={materials['Material.006']} position={[-0.086, 0.09, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body48002.geometry} material={materials['Material.006']} position={[-0.069, 0.232, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body49002.geometry} material={materials['Material.006']} position={[-0.173, 0.232, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body50002.geometry} material={materials['Material.006']} position={[-0.173, 0.127, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body51002.geometry} material={materials['Material.006']} position={[-0.068, 0.233, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body52002.geometry} material={materials['Material.006']} position={[-0.174, 0.233, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body53002.geometry} material={materials['Material.006']} position={[-0.174, 0.126, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body54002.geometry} material={materials['Material.006']} position={[-0.068, 0.126, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body55002.geometry} material={materials['Material.006']} position={[-0.121, 0.18, -0.082]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body56002.geometry} material={materials['Material.006']} position={[-0.069, 0.127, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body3014.geometry} material={materials['Old rubber']} position={[0.002, 0.153, 0.005]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body91003.geometry} material={materials.wheel_side_metal} position={[0.301, 0.162, -0.006]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body1016.geometry} material={materials['Opaque(255,255,255)']} position={[0.099, 0.253, 0.1]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body2016.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.253, 0.165]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body3016.geometry} material={materials['Opaque(255,255,255)']} position={[-0.096, 0.253, 0.1]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body4016.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.253, 0.035]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body5016.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.23, 0.1]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body6016.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.277, 0.1]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Body1017.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.15, 0.088]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body2017.geometry} material={materials['Opaque(255,255,255)']} position={[-0.079, 0.15, 0.008]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body3017.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.15, -0.072]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body4017.geometry} material={materials['Opaque(255,255,255)']} position={[0.081, 0.15, 0.008]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body5017.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.07, 0.008]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body6017.geometry} material={materials['Opaque(255,255,255)']} position={[0.001, 0.23, 0.008]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body1018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.141, -0.158]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body2018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.141, -0.165]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body3018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.141, -0.168]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body4018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.141, -0.165]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body5018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.141, -0.158]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body6018.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.141, -0.155]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body7015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.144, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body8015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.138, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body9015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.009, 0.141, -0.125]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body10015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.003, 0.141, -0.129]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body11015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.141, -0.135]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body12015.geometry} material={materials['Opaque(255,255,255)']} position={[-0.011, 0.141, -0.138]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body13013.geometry} material={materials['Opaque(255,255,255)']} position={[-0.016, 0.141, -0.134]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body14013.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.141, -0.127]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body15010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.144, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body16010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.138, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body17010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.147, -0.16]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body18010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.006, 0.147, -0.166]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body19010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.011, 0.147, -0.167]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body20010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.147, -0.162]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body21010.geometry} material={materials['Opaque(255,255,255)']} position={[-0.013, 0.147, -0.157]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body22009.geometry} material={materials['Opaque(255,255,255)']} position={[-0.008, 0.147, -0.156]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body23008.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.15, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body24008.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.144, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body25006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.147, -0.128]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body26006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.147, -0.134]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body27006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.147, -0.137]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body28006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.147, -0.134]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body29006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.147, -0.128]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body30006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.147, -0.125]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body31006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.15, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body32006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.144, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body33006.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.071, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body34006.geometry} material={materials['Opaque(255,255,255)']} position={[0.002, 0.094, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body35006.geometry} material={materials['Opaque(255,255,255)']} position={[0.013, 0.099, -0.125]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body36006.geometry} material={materials['Opaque(255,255,255)']} position={[0.013, 0.099, -0.171]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body37005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.025, 0.132, -0.124]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body38005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.025, 0.132, -0.169]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body39005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.007, 0.146, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body40005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.007, 0.146, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body41005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.004, 0.141, -0.147]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body42005.geometry} material={materials['Opaque(255,255,255)']} position={[0.008, 0.124, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body43005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.005, 0.119, -0.118]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body44005.geometry} material={materials['Opaque(255,255,255)']} position={[0.014, 0.1, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body45005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.005, 0.119, -0.175]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body46005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.034, 0.121, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body47005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.115, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body48005.geometry} material={materials['Opaque(255,255,255)']} position={[0.002, 0.131, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body49005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.021, 0.132, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body50005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.138, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body51005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.027, 0.126, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body52005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.141, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body53005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.143, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body54005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.012, 0.146, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body55005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.153, -0.161]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body56005.geometry} material={materials['Opaque(255,255,255)']} position={[-0.012, 0.146, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body57004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.153, -0.131]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body58004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.029, 0.132, -0.169]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body59004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.027, 0.138, -0.169]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body60004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.029, 0.132, -0.124]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body61004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.027, 0.138, -0.124]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body62004.geometry} material={materials['Opaque(255,255,255)']} position={[0.012, 0.099, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body63004.geometry} material={materials['Opaque(255,255,255)']} position={[0.013, 0.091, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body64004.geometry} material={materials['Opaque(255,255,255)']} position={[0.013, 0.099, -0.168]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body65004.geometry} material={materials['Opaque(255,255,255)']} position={[0.013, 0.099, -0.121]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body66004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.022, 0.094, -0.147]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body67004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.073, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body68004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.015, 0.071, -0.147]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body69004.geometry} material={materials['Opaque(255,255,255)']} position={[-0.01, 0.07, -0.146]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Body18019.geometry} material={materials['black_wheel.001']} position={[0.294, 0.205, 0.336]} rotation={[1.428, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes.Body12028.geometry} material={materials.Steel} position={[0.294, 0.085, 0.238]} rotation={[1.178, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body1036.geometry} material={materials['Opaque(255,255,255)']} position={[-0.087, 0.131, -0.3]} rotation={[-0.805, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body21020.geometry} material={materials['Opaque(255,255,255)']} position={[-0.087, 0.128, -0.303]} rotation={[-0.805, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body1037.geometry} material={materials['Material.006']} position={[0.155, 0.089, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body2037.geometry} material={materials['Material.006']} position={[0.085, 0.089, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body3037.geometry} material={materials['Material.006']} position={[0.085, 0.193, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body4037.geometry} material={materials['Material.006']} position={[0.155, 0.193, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body5037.geometry} material={materials['Material.006']} position={[0.158, 0.142, -0.259]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body6037.geometry} material={materials['Material.006']} position={[0.158, 0.142, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body7034.geometry} material={materials['Material.006']} position={[0.088, 0.142, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body8034.geometry} material={materials['Material.006']} position={[0.088, 0.142, -0.259]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body9034.geometry} material={materials['Material.006']} position={[0.078, 0.151, -0.303]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body10034.geometry} material={materials['Material.006']} position={[0.168, 0.151, -0.301]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body11034.geometry} material={materials['Material.006']} position={[0.123, 0.122, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body12034.geometry} material={materials['Material.006']} position={[0.123, 0.136, -0.292]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body13031.geometry} material={materials['Material.006']} position={[0.123, 0.097, -0.242]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body14031.geometry} material={materials['Material.006']} position={[0.08, 0.131, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body15021.geometry} material={materials['Material.006']} position={[0.167, 0.131, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body16021.geometry} material={materials['Material.006']} position={[0.123, 0.07, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body17021.geometry} material={materials['Material.006']} position={[0.123, 0.141, -0.362]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body18021.geometry} material={materials['Material.006']} position={[0.123, 0.214, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body19021.geometry} material={materials['Material.006']} position={[0.123, 0.136, -0.311]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body20021.geometry} material={materials['Material.006']} position={[0.123, 0.143, -0.306]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body21021.geometry} material={materials['Material.006']} position={[0.123, 0.145, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body22019.geometry} material={materials['Material.006']} position={[0.123, 0.143, -0.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body23018.geometry} material={materials['Material.006']} position={[0.169, 0.129, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body24018.geometry} material={materials['Material.006']} position={[0.168, 0.108, -0.303]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body25008.geometry} material={materials['Material.006']} position={[0.077, 0.129, -0.302]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body26008.geometry} material={materials['Material.006']} position={[0.078, 0.108, -0.301]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body27008.geometry} material={materials['Material.006']} position={[0.174, 0.231, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body28008.geometry} material={materials['Material.006']} position={[0.123, 0.235, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body29008.geometry} material={materials['Material.006']} position={[0.072, 0.231, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body30008.geometry} material={materials['Material.006']} position={[0.068, 0.18, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body31008.geometry} material={materials['Material.006']} position={[0.072, 0.128, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body32008.geometry} material={materials['Material.006']} position={[0.123, 0.125, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body33008.geometry} material={materials['Material.006']} position={[0.174, 0.128, -0.232]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body34008.geometry} material={materials['Material.006']} position={[0.178, 0.18, -0.188]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body35008.geometry} material={materials['Material.006']} position={[0.123, 0.178, -0.242]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body36008.geometry} material={materials['Material.006']} position={[0.088, 0.142, -0.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body37007.geometry} material={materials['Material.006']} position={[0.088, 0.142, -0.344]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body38007.geometry} material={materials['Material.006']} position={[0.158, 0.142, -0.344]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body39007.geometry} material={materials['Material.006']} position={[0.158, 0.142, -0.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body40007.geometry} material={materials['Material.006']} position={[0.161, 0.194, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body41007.geometry} material={materials['Material.006']} position={[0.158, 0.194, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body42007.geometry} material={materials['Material.006']} position={[0.091, 0.194, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body43007.geometry} material={materials['Material.006']} position={[0.088, 0.194, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body44007.geometry} material={materials['Material.006']} position={[0.091, 0.09, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body45007.geometry} material={materials['Material.006']} position={[0.088, 0.09, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body46007.geometry} material={materials['Material.006']} position={[0.161, 0.09, -0.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body47007.geometry} material={materials['Material.006']} position={[0.158, 0.09, -0.352]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body48007.geometry} material={materials['Material.006']} position={[0.175, 0.232, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body49007.geometry} material={materials['Material.006']} position={[0.071, 0.232, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body50007.geometry} material={materials['Material.006']} position={[0.071, 0.127, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body51007.geometry} material={materials['Material.006']} position={[0.176, 0.233, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body52007.geometry} material={materials['Material.006']} position={[0.07, 0.233, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body53007.geometry} material={materials['Material.006']} position={[0.07, 0.126, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body54007.geometry} material={materials['Material.006']} position={[0.176, 0.126, -0.152]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body55007.geometry} material={materials['Material.006']} position={[0.123, 0.18, -0.082]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Body56007.geometry} material={materials['Material.006']} position={[0.175, 0.127, -0.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.ring_5001.geometry} material={materials.black_metal_1} position={[-0.006, 0.614, -0.303]} scale={0.001} />
      <group position={[-0.001, 0.357, 0.162]} scale={0.001}>
        <mesh geometry={nodes['base_plate_(1)_1'].geometry} material={materials.texture} />
        <mesh geometry={nodes['base_plate_(1)_2'].geometry} material={materials.black_metal} />
      </group>
      <mesh geometry={nodes.Body2045.geometry} material={materials.texture} position={[0.299, 0.402, 0.157]} scale={0.001} />
      <mesh geometry={nodes.Body2002.geometry} material={materials.texture} position={[-0.301, 0.402, 0.157]} scale={0.001} />
      <mesh geometry={nodes['1_left'].geometry} material={materials.texture} position={[0.3, 0.448, 0.293]} rotation={[0, -0.262, 0]} />
      <mesh geometry={nodes.body2001.geometry} material={materials.texture} position={[0.35, 0.53, 0.373]} rotation={[-0.625, -0.215, -0.148]} scale={0.001} />
      <mesh geometry={nodes['2'].geometry} material={materials.texture} position={[-0.22, 0.53, 0.342]} rotation={[-0.459, 0.177, 0.087]} scale={0.001} />
      <mesh geometry={nodes.body4_001.geometry} material={materials.texture} position={[0.362, 0.78, 0.195]} rotation={[-0.607, -0.217, -0.144]} scale={0.001} />
      <mesh geometry={nodes.body4_005.geometry} material={materials.texture} position={[-0.279, 0.805, 0.218]} rotation={[-0.459, 0.177, 0.087]} scale={0.001} />
      <mesh geometry={nodes.body4_004.geometry} material={materials.texture} position={[0.318, 0.803, 0.219]} rotation={[-0.686, -0.177, -0.192]} scale={0.001} />
      <mesh geometry={nodes.body4_006.geometry} material={materials.texture} position={[-0.307, 0.823, 0.262]} rotation={[-0.575, 0.166, 0.106]} scale={0.001} />
      <mesh geometry={nodes.body5001.geometry} material={materials.texture} position={[0.301, 0.916, 0.362]} rotation={[-0.73, -0.17, -0.198]} scale={0.001} />
      <mesh geometry={nodes.body5004.geometry} material={materials.texture} position={[-0.261, 0.92, 0.41]} rotation={[-0.678, 0.154, 0.123]} scale={0.001} />
      <mesh geometry={nodes.Body109007.geometry} material={materials.black_metal_1} position={[0.304, 0.937, 0.413]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <group position={[0.269, 0.919, 0.414]} rotation={[-1.345, -0.022, -0.259]} scale={0.001}>
        <mesh geometry={nodes.box_pcb.geometry} material={materials.black_metal_1} />
        <mesh geometry={nodes.box_pcb_1.geometry} material={materials.texture} />
        <mesh geometry={nodes.box_pcb_2.geometry} material={materials.orange} />
      </group>
      <mesh geometry={nodes.jaw_2002.geometry} material={materials.black_metal_1} position={[0.245, 0.876, 0.54]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.logo_cap.geometry} material={materials.texture} position={[0.267, 0.943, 0.412]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.logo_scale.geometry} material={materials.orange} position={[0.268, 0.948, 0.413]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.servo_cap.geometry} material={materials.black_metal_1} position={[0.251, 0.898, 0.42]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.Body1048.geometry} material={materials.black_metal_1} position={[0.231, 0.876, 0.515]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.jaw_1.geometry} material={materials.black_metal_1} position={[0.204, 0.867, 0.527]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.shaft_b.geometry} material={materials.Steel} position={[0.241, 0.889, 0.459]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes['servo_real_(1)'].geometry} material={materials['Opaque(245,245,246)']} position={[0.264, 0.901, 0.407]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.servo_real002.geometry} material={materials.black_metal_1} position={[0.242, 0.882, 0.491]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.shaft_a002.geometry} material={materials.Steel} position={[0.248, 0.895, 0.433]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.SLIP_RING.geometry} material={materials.Steel} position={[0.246, 0.894, 0.44]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes['SLIP_RING_HOLDER_(1)'].geometry} material={materials.black_metal_1} position={[0.258, 0.9, 0.43]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.TOP_servo_cap.geometry} material={materials.black_metal_1} position={[0.268, 0.904, 0.393]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.tpu_cover002.geometry} material={materials.black_metal_1} position={[0.245, 0.867, 0.557]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.Curve001.geometry} material={materials.orange} position={[0.409, 0.762, 0.222]} rotation={[-0.625, -0.215, -0.148]} />
      <mesh geometry={nodes['rover_plate_front_(1)'].geometry} material={materials.texture} position={[0.004, 0.349, 0.129]} scale={0.001} />
      <mesh geometry={nodes['rover_plate_back_(1)'].geometry} material={materials.black_metal} position={[0.05, 0.349, -0.221]} scale={0.001} />
      <mesh geometry={nodes['camera_mount__Oak_D_(1)'].geometry} material={materials.texture} position={[0, 0.73, 0.04]} scale={0.001} />
      <mesh geometry={nodes.Body18023.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0.001, 0.775, 0.052]} scale={0.001} />
      <mesh geometry={nodes.Body22021.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0.001, 0.711, 0.013]} scale={0.001} />
      <mesh geometry={nodes.Body23020.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.015, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body24020.geometry} material={materials['ABS (White) (1) (1) (1) (1)']} position={[-0.072, 0.792, 0.038]} scale={0.001} />
      <mesh geometry={nodes.Body26010.geometry} material={materials.orange} position={[0.074, 0.79, 0.037]} scale={0.001} />
      <mesh geometry={nodes.Body27010.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.001, 0.768, 0.028]} scale={0.001} />
      <mesh geometry={nodes.Body51009.geometry} material={materials['ABS (White) (1) (1)']} position={[-0.036, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body52009.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0, 0.754, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body53009.geometry} material={materials['ABS (White) (1) (1)']} position={[-0.019, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body54009.geometry} material={materials['ABS (White) (1) (1)']} position={[-0.01, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body55009.geometry} material={materials['ABS (White) (1) (1)']} position={[-0.028, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body56009.geometry} material={materials['ABS (White) (1) (1)']} position={[-0.045, 0.732, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body57007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.001, 0.797, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body58007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.008, 0.75, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body59007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.037, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body60007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.03, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body61007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.024, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body62007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.007, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body63007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.013, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body64007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.01, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body65007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.017, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body66007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.02, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body67007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.027, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body68007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.034, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body69007.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.041, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body70006.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0.024, 0.738, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body73006.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0.001, 0.689, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body74006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.019, 0.739, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body79006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.001, 0.688, 0.05]} scale={0.001} />
      <mesh geometry={nodes.Body81006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.039, 0.688, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body84006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.043, 0.691, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body85006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.047, 0.693, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body86006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.035, 0.685, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body87006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[-0.052, 0.696, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body88006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.053, 0.696, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body89006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.045, 0.691, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body90006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.041, 0.688, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body91006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.049, 0.693, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body92006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0.037, 0.685, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body93006.geometry} material={materials['ABS (White) (1) (1) (1)']} position={[0, 0.69, 0.068]} scale={0.001} />
      <mesh geometry={nodes.front.geometry} material={materials['ABS (White) (1) (1) (1) (2)']} position={[0, 0.738, 0.067]} scale={0.001} />
      <mesh geometry={nodes.Body96006.geometry} material={materials['ABS (White) (1).001']} position={[-0.002, 0.689, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body97006.geometry} material={materials['ABS (White) (1).001']} position={[0.004, 0.689, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body98006.geometry} material={materials['ABS (White) (1).001']} position={[-0.002, 0.684, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body99006.geometry} material={materials['ABS (White) (1).001']} position={[0.004, 0.694, 0.068]} scale={0.001} />
      <mesh geometry={nodes.Body104006.geometry} material={materials['glass.001']} position={[0.001, 0.762, 0.066]} scale={0.001} />
      <mesh geometry={nodes.driver_box.geometry} material={materials.black_metal_1} position={[0.308, 0.423, 0.049]} scale={0.001} />
      <mesh geometry={nodes.spine_main_cover.geometry} material={materials.orange} position={[0.001, 0.458, 0.067]} scale={0.001} />
      <mesh geometry={nodes['spine_main_cover_(1)'].geometry} material={materials.orange} position={[0.001, 0.493, 0.067]} scale={0.001} />
      <mesh geometry={nodes['spine_main_cover_(2)'].geometry} material={materials.orange} position={[0.001, 0.529, 0.067]} scale={0.001} />
      <mesh geometry={nodes['spine_main_cover_(3)'].geometry} material={materials.orange} position={[0.001, 0.564, 0.067]} scale={0.001} />
      <mesh geometry={nodes['spine_main_cover_(4)'].geometry} material={materials.orange} position={[0.001, 0.599, 0.067]} scale={0.001} />
      <mesh geometry={nodes.neack_top.geometry} material={materials['ABS (White) (1)']} position={[0, 0.661, 0.039]} scale={0.001} />
      <mesh geometry={nodes.base_plate.geometry} material={materials['ABS (White) (1)']} position={[0, 0.398, 0.039]} scale={0.001} />
      <mesh geometry={nodes['spine_main_cover_(5)'].geometry} material={materials.orange} position={[0.001, 0.635, 0.067]} scale={0.001} />
      <mesh geometry={nodes.neack.geometry} material={materials['ABS (White) (1)']} position={[0, 0.605, 0.04]} scale={0.001} />
      <mesh geometry={nodes.spine_scale.geometry} material={materials['ABS (White) (1)']} position={[0, 0.516, 0.039]} scale={0.001} />
      <mesh geometry={nodes['Pivot_Base_(1)'].geometry} material={materials.black_metal} position={[0, 0.368, 0.005]} scale={0.001} />
      <mesh geometry={nodes.Bearing_Shaft.geometry} material={materials.texture} position={[0, 0.391, 0.038]} scale={0.001} />
      <mesh geometry={nodes['Bearing_rail_support_(1)'].geometry} material={materials.black_metal} position={[-0.018, 0.38, 0.038]} scale={0.001} />
      <mesh geometry={nodes['Bearing_rail_support_(1)_(1)'].geometry} material={materials.black_metal} position={[0.019, 0.38, 0.038]} scale={0.001} />
      <mesh geometry={nodes.Body2014.geometry} material={materials.black_metal} position={[0.299, 0.402, 0.157]} scale={0.001} />
      <mesh geometry={nodes.Body2003.geometry} material={materials.black_metal} position={[-0.301, 0.402, 0.157]} scale={0.001} />
      <mesh geometry={nodes.Body2044.geometry} material={materials.steel_1} position={[0.299, 0.402, 0.157]} scale={0.001} />
      <mesh geometry={nodes.Body2004.geometry} material={materials.steel_1} position={[-0.301, 0.402, 0.157]} scale={0.001} />
      <group position={[0.001, 0.762, 0.056]} scale={0.001}>
        <mesh geometry={nodes.Body104002.geometry} material={materials.glass} />
        <mesh geometry={nodes.Body104002_1.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.rear.geometry} material={materials.texture} position={[0, 0.339, 0.392]} />
      <mesh geometry={nodes.front002.geometry} material={materials.texture} position={[0, 0.318, -0.446]} />
      <mesh geometry={nodes['driver_box_(1)'].geometry} material={materials.black_metal_1} position={[-0.308, 0.423, 0.051]} scale={0.001} />
      <group position={[-0.3, 0.448, 0.293]} rotation={[0, 0.197, 0]}>
        <mesh geometry={nodes['Body1_(1)001'].geometry} material={materials.texture} />
        <mesh geometry={nodes['Body1_(1)001_1'].geometry} material={materials.Steel} />
        <mesh geometry={nodes['Body1_(1)001_2'].geometry} material={materials.black_metal} />
      </group>
      <group position={[-0.275, 0.914, 0.432]} rotation={[0.297, 0.188, -0.057]}>
        <mesh geometry={nodes.Body1076.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1076_1.geometry} material={materials.black_metal_1} />
      </group>
      <mesh geometry={nodes.Body1062.geometry} material={materials['Procedural Stainless Steel']} position={[-0.212, 0.855, 0.589]} rotation={[0.561, 0.167, -0.104]} />
      <mesh geometry={nodes.Body1065.geometry} material={materials['Procedural Stainless Steel']} position={[-0.207, 0.842, 0.613]} rotation={[1.043, 0.1, -0.17]} />
      <group position={[-0.204, 0.822, 0.624]} rotation={[1.76, -0.037, -0.193]}>
        <mesh geometry={nodes.Body1010.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1010_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.233, 0.874, 0.53]} rotation={[0.297, 0.188, -0.219]}>
        <mesh geometry={nodes.Body1013.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1013_1.geometry} material={materials.black_metal_1} />
      </group>
      <group position={[-0.19, 0.835, 0.521]} rotation={[0.06, -0.005, -0.157]}>
        <mesh geometry={nodes.Body1012.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1012_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Body1066.geometry} material={materials['Procedural Stainless Steel']} position={[-0.232, 0.855, 0.593]} rotation={[0.421, 0.18, -0.08]} />
      <mesh geometry={nodes.Body1068.geometry} material={materials['Procedural Stainless Steel']} position={[-0.227, 0.846, 0.618]} rotation={[1.022, 0.104, -0.167]} />
      <group position={[-0.224, 0.826, 0.63]} rotation={[1.564, 0.001, -0.197]}>
        <mesh geometry={nodes.Body1007.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1007_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Body1069.geometry} material={materials['Procedural Stainless Steel']} position={[-0.253, 0.855, 0.597]} rotation={[0.553, 0.168, -0.103]} />
      <mesh geometry={nodes.Body1071.geometry} material={materials['Procedural Stainless Steel']} position={[-0.248, 0.842, 0.621]} rotation={[0.85, 0.131, -0.147]} />
      <group position={[-0.244, 0.825, 0.636]} rotation={[1.388, 0.036, -0.193]}>
        <mesh geometry={nodes.Body1019.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1019_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Body1072.geometry} material={materials['Procedural Stainless Steel']} position={[-0.273, 0.855, 0.601]} rotation={[0.451, 0.177, -0.085]} />
      <mesh geometry={nodes.Body1074.geometry} material={materials['Procedural Stainless Steel']} position={[-0.268, 0.845, 0.626]} rotation={[0.749, 0.145, -0.133]} />
      <group position={[-0.264, 0.829, 0.643]} rotation={[1.318, 0.05, -0.19]}>
        <mesh geometry={nodes.Body1023.geometry} material={materials['Procedural Stainless Steel']} />
        <mesh geometry={nodes.Body1023_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Curve002.geometry} material={materials.orange} position={[-0.225, 0.784, 0.218]} rotation={[-0.459, 0.177, 0.087]} />
    </group>
  )
}

useGLTF.preload('../../../assets/ThreeD/EclipseRobot.glb')
