/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/ThreeD/MeshNetworkCommunication.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MeshNetworkCommunication(props) {
  const { nodes, materials } = useGLTF('../../../assets/ThreeD/MeshNetworkCommunication.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group rotation={[Math.PI / 2, 0, -Math.PI / 6]}>
          <group position={[23.58, 40.842, -1269.016]} rotation={[0, 0, -2.516]}>
            <mesh geometry={nodes.Body1002.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[23.58, 40.842, -1266.016]}>
            <mesh geometry={nodes.Body1003.geometry} material={materials['Steel - Satin']} scale={10} />
          </group>
          <group position={[23.58, 40.842, -910.016]}>
            <mesh geometry={nodes.Body1004.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[23.58, 40.842, -60.016]}>
            <mesh geometry={nodes.Body1.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[86.529, -30.188, -188.352]} rotation={[0.834, 0.404, -1.228]}>
            <mesh geometry={nodes.Body1001.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[-69.408, 18.842, -188.352]} rotation={[0, -0.905, 0]}>
            <mesh geometry={nodes.Body1009.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[51.022, 132.373, -188.352]} rotation={[-0.834, 0.404, -1.913]}>
            <mesh geometry={nodes.Body1010.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[23.58, 40.842, -685.084]} rotation={[0, 0, Math.PI / 6]}>
            <mesh geometry={nodes.Body1007.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[-16.643, 40.842, -700.586]} rotation={[0, -0.354, 0]}>
            <mesh geometry={nodes.Body1005.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[43.692, 75.677, -700.586]} rotation={[-0.31, 0.174, -2.067]}>
            <mesh geometry={nodes.Body1011.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[43.692, 6.008, -700.586]} rotation={[0.31, 0.174, 2.067]}>
            <mesh geometry={nodes.Body1012.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[172.094, -216.39, -6.575]} rotation={[0.31, 0.174, -0.027]}>
            <mesh geometry={nodes.Body1006.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[172.094, 298.075, -6.575]} rotation={[-0.31, 0.174, 0.027]}>
            <mesh geometry={nodes.Body1013.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[-273.446, 40.842, -6.575]} rotation={[0, -0.354, -2.535]}>
            <mesh geometry={nodes.Body1014.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
          <group position={[40.676, 17.16, -949.016]} rotation={[1.513, -0.945, 3.095]}>
            <mesh geometry={nodes.Body1008.geometry} material={materials['Paint - Metallic (Dark Grey)']} scale={10} />
          </group>
        </group>
        <mesh geometry={nodes.Body2001.geometry} material={materials['Material.001']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../assets/ThreeD/MeshNetworkCommunication.glb')
