/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/ThreeD/ModularToolAttachments.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModularToolAttachments(props) {
  const { nodes, materials } = useGLTF('../../../assets/ThreeD/ModularToolAttachments.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.001, 0.084, 0]} rotation={[0, -0.262, 0]}>
        <mesh geometry={nodes['Body1_(1)001'].geometry} material={materials['texture.001']} />
        <mesh geometry={nodes['Body1_(1)001_1'].geometry} material={materials['Steel.001']} />
        <mesh geometry={nodes['Body1_(1)001_2'].geometry} material={materials['black_metal.001']} />
      </group>
      <group position={[0.051, 0.166, 0.08]} rotation={[-0.625, -0.215, -0.148]} scale={0.001}>
        <mesh geometry={nodes.body2001.geometry} material={materials['texture.001']} />
        <mesh geometry={nodes.body2001_1.geometry} material={materials['Steel.001']} />
        <mesh geometry={nodes.body2001_2.geometry} material={materials['black_metal.001']} />
        <mesh geometry={nodes.body2001_3.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.063, 0.416, -0.097]} rotation={[-0.607, -0.217, -0.144]} scale={0.001}>
        <mesh geometry={nodes.body4_001.geometry} material={materials['texture.001']} />
        <mesh geometry={nodes.body4_001_1.geometry} material={materials['Steel.001']} />
        <mesh geometry={nodes.body4_001_2.geometry} material={materials['black_metal_1.001']} />
      </group>
      <group position={[0.019, 0.439, -0.074]} rotation={[-0.686, -0.177, -0.192]} scale={0.001}>
        <mesh geometry={nodes.body4_004.geometry} material={materials['texture.001']} />
        <mesh geometry={nodes.body4_004_1.geometry} material={materials['black_metal.001']} />
      </group>
      <group position={[0.002, 0.552, 0.069]} rotation={[-0.73, -0.17, -0.198]} scale={0.001}>
        <mesh geometry={nodes.body5001.geometry} material={materials['texture.001']} />
        <mesh geometry={nodes.body5001_1.geometry} material={materials['black_metal.001']} />
        <mesh geometry={nodes.body5001_2.geometry} material={materials['Steel - Satin.002']} />
      </group>
      <mesh geometry={nodes.Body109001.geometry} material={materials['black_metal_1.001']} position={[0.005, 0.573, 0.12]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <group position={[-0.03, 0.555, 0.121]} rotation={[-1.345, -0.022, -0.259]} scale={0.001}>
        <mesh geometry={nodes.box_pcb002.geometry} material={materials['texture.001']} />
        <mesh geometry={nodes.box_pcb002_1.geometry} material={materials['orange.001']} />
        <mesh geometry={nodes.box_pcb002_2.geometry} material={materials['black_metal_1.001']} />
      </group>
      <mesh geometry={nodes.jaw_2001.geometry} material={materials['black_metal_1.001']} position={[-0.054, 0.512, 0.247]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.logo_cap001.geometry} material={materials['texture.001']} position={[-0.032, 0.579, 0.119]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.logo_scale001.geometry} material={materials['orange.001']} position={[-0.031, 0.584, 0.12]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.servo_cap001.geometry} material={materials['black_metal_1.001']} position={[-0.048, 0.534, 0.127]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.Body1003.geometry} material={materials['black_metal_1.001']} position={[-0.068, 0.512, 0.222]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.jaw_1001.geometry} material={materials['black_metal_1.001']} position={[-0.095, 0.503, 0.234]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.shaft_b001.geometry} material={materials['Steel.001']} position={[-0.058, 0.525, 0.167]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes['servo_real_(1)001'].geometry} material={materials['Opaque(245,245,246).001']} position={[-0.035, 0.537, 0.115]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.servo_real001.geometry} material={materials['black_metal_1.001']} position={[-0.057, 0.518, 0.198]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.shaft_a001.geometry} material={materials['Steel.001']} position={[-0.051, 0.531, 0.141]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes['SLIP_RING_HOLDER_(1)001'].geometry} material={materials['black_metal_1.001']} position={[-0.041, 0.536, 0.137]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.SLIP_RING001.geometry} material={materials['Steel.001']} position={[-0.053, 0.53, 0.147]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.TOP_servo_cap001.geometry} material={materials['black_metal_1.001']} position={[-0.031, 0.54, 0.101]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.tpu_cover001.geometry} material={materials['black_metal_1.001']} position={[-0.054, 0.503, 0.264]} rotation={[-1.345, -0.022, -0.259]} scale={0.001} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['orange.001']} position={[0.11, 0.398, -0.071]} rotation={[-0.625, -0.215, -0.148]} />
    </group>
  )
}

useGLTF.preload('../../../assets/ThreeD//ModularToolAttachments.glb')
